package com.zhaoyun.docmanager.model.dvo;

import java.util.Date;

public class DocAppMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.id
     * 消息主键
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.app_id
     * 应用主键
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.topic
     * 消息topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.message_type
     * 消息类型
     *
     * @mbggenerated
     */
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.message_object_name
     * 消息对象名
     *
     * @mbggenerated
     */
    private String messageObjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.desc
     * 消息说明
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.cause
     * 产生条件
     *
     * @mbggenerated
     */
    private String cause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.create_time
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.create_person
     * 创建人
     *
     * @mbggenerated
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.update_time
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.update_person
     * 更新人
     *
     * @mbggenerated
     */
    private String updatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_app_message.message_object_json
     * 消息对象json
     *
     * @mbggenerated
     */
    private String messageObjectJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.id
     *
     * @return the value of doc_app_message.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.id
     *
     * @param id the value for doc_app_message.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.app_id
     *
     * @return the value of doc_app_message.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.app_id
     *
     * @param appId the value for doc_app_message.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.topic
     *
     * @return the value of doc_app_message.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.topic
     *
     * @param topic the value for doc_app_message.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.message_type
     *
     * @return the value of doc_app_message.message_type
     *
     * @mbggenerated
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.message_type
     *
     * @param messageType the value for doc_app_message.message_type
     *
     * @mbggenerated
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.message_object_name
     *
     * @return the value of doc_app_message.message_object_name
     *
     * @mbggenerated
     */
    public String getMessageObjectName() {
        return messageObjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.message_object_name
     *
     * @param messageObjectName the value for doc_app_message.message_object_name
     *
     * @mbggenerated
     */
    public void setMessageObjectName(String messageObjectName) {
        this.messageObjectName = messageObjectName == null ? null : messageObjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.desc
     *
     * @return the value of doc_app_message.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.desc
     *
     * @param desc the value for doc_app_message.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.cause
     *
     * @return the value of doc_app_message.cause
     *
     * @mbggenerated
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.cause
     *
     * @param cause the value for doc_app_message.cause
     *
     * @mbggenerated
     */
    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.create_time
     *
     * @return the value of doc_app_message.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.create_time
     *
     * @param createTime the value for doc_app_message.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.create_person
     *
     * @return the value of doc_app_message.create_person
     *
     * @mbggenerated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.create_person
     *
     * @param createPerson the value for doc_app_message.create_person
     *
     * @mbggenerated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.update_time
     *
     * @return the value of doc_app_message.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.update_time
     *
     * @param updateTime the value for doc_app_message.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.update_person
     *
     * @return the value of doc_app_message.update_person
     *
     * @mbggenerated
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.update_person
     *
     * @param updatePerson the value for doc_app_message.update_person
     *
     * @mbggenerated
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson == null ? null : updatePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doc_app_message.message_object_json
     *
     * @return the value of doc_app_message.message_object_json
     *
     * @mbggenerated
     */
    public String getMessageObjectJson() {
        return messageObjectJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doc_app_message.message_object_json
     *
     * @param messageObjectJson the value for doc_app_message.message_object_json
     *
     * @mbggenerated
     */
    public void setMessageObjectJson(String messageObjectJson) {
        this.messageObjectJson = messageObjectJson == null ? null : messageObjectJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_message
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", topic=").append(topic);
        sb.append(", messageType=").append(messageType);
        sb.append(", messageObjectName=").append(messageObjectName);
        sb.append(", desc=").append(desc);
        sb.append(", cause=").append(cause);
        sb.append(", createTime=").append(createTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updatePerson=").append(updatePerson);
        sb.append(", messageObjectJson=").append(messageObjectJson);
        sb.append("]");
        return sb.toString();
    }
}