/**
 * com Inc
 * Copyright (c) 2014-2016 All Rights Reserved.
 */
package com.zhaoyun.docmanager.model.vo;

import java.util.Date;

import org.apache.commons.lang3.StringUtils;

/**
 * 
 * @author user
 * @version $Id: DocApiVo.java, v 0.1 2016年8月29日 下午8:41:45 user Exp $
 */
public class DocApiVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.id
     * api主键
     *
     * @mbggenerated
     */
    private Integer     id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.service_id
     * 服务主键
     *
     * @mbggenerated
     */
    private Integer     serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.is_deprecated
     * 是否废弃(0：否；1：是；默认：否)
     *
     * @mbggenerated
     */
    private Integer     isDeprecated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.name
     * api名称
     *
     * @mbggenerated
     */
    private String      name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.sign
     * api签名
     *
     * @mbggenerated
     */
    private String      sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.full_name
     * api全限定名
     *
     * @mbggenerated
     */
    private String      fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.desc
     * api介绍
     *
     * @mbggenerated
     */
    private String      desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.create_time
     * 创建时间
     *
     * @mbggenerated
     */
    private Date        createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.create_person
     * 创建人
     *
     * @mbggenerated
     */
    private String      createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.update_time
     * 修改时间
     *
     * @mbggenerated
     */
    private Date        updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.update_person
     * 更新人
     *
     * @mbggenerated
     */
    private String      updatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.param_in
     * api入参
     *
     * @mbggenerated
     */
    private String      paramIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.param_out
     * api出参
     *
     * @mbggenerated
     */
    private String      paramOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.ch_name
     * 注释@name
     *
     * @mbggenerated
     */
    private String      chName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.author
     * @author
     *
     * @mbggenerated
     */
    private String      author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_api.date
     * @date
     *
     * @mbggenerated
     */
    private String      date;
    /**
     * 调用信息
     */
    private ChainInfoVo chainInfoVo;

    public ChainInfoVo getChainInfoVo() {
        return chainInfoVo;
    }

    public void setChainInfoVo(ChainInfoVo chainInfoVo) {
        this.chainInfoVo = chainInfoVo;
    }

    public String getChName() {
        return chName;
    }

    public void setChName(String chName) {
        this.chName = chName;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getServiceId() {
        return serviceId;
    }

    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    public Integer getIsDeprecated() {
        return isDeprecated;
    }

    public void setIsDeprecated(Integer isDeprecated) {
        this.isDeprecated = isDeprecated;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getCreatePerson() {
        return createPerson;
    }

    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getUpdatePerson() {
        return updatePerson;
    }

    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    public String getParamIn() {
        return paramIn;
    }

    public void setParamIn(String paramIn) {
        this.paramIn = paramIn;
    }

    public String getParamOut() {
        return paramOut;
    }

    public void setParamOut(String paramOut) {
        this.paramOut = paramOut;
    }

    public String getShowName() {
        if (StringUtils.isNoneBlank(chName)) {
            return chName;
        }
        return desc;
    }

    @Override
    public String toString() {
        return "DocApiVo{" + "author='" + author + '\'' + ", id=" + id + ", serviceId=" + serviceId
               + ", isDeprecated=" + isDeprecated + ", name='" + name + '\'' + ", sign='" + sign
               + '\'' + ", fullName='" + fullName + '\'' + ", desc='" + desc + '\''
               + ", createTime=" + createTime + ", createPerson='" + createPerson + '\''
               + ", updateTime=" + updateTime + ", updatePerson='" + updatePerson + '\''
               + ", paramIn='" + paramIn + '\'' + ", paramOut='" + paramOut + '\'' + ", chName='"
               + chName + '\'' + ", date='" + date + '\'' + ", chainInfoVo=" + chainInfoVo + '}';
    }
}
