/**
 * com Inc
 * Copyright (c) 2014-2016 All Rights Reserved.
 */
package com.zhaoyun.docmanager.model.param;

/**
 * 
 * @author user
 * @version $Id: ApiQueryPram.java, v 0.1 2016年8月15日 下午5:43:43 user Exp $
 */
public class ApiQueryParam extends PagedQueryParam {

    /**  */
    private static final long serialVersionUID = 1L;

    /**  服务主键*/
    private Integer           serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_service.is_deprecated
     * 是否废弃(0：否；1：是；默认：否)
     *
     * @mbggenerated
     */
    private Integer           isDeprecated;

    public Integer getIsDeprecated() {
        return isDeprecated;
    }

    public void setIsDeprecated(Integer isDeprecated) {
        this.isDeprecated = isDeprecated;
    }

    /**
     * Getter method for property <tt>serviceId</tt>.
     * 
     * @return property value of serviceId
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * Setter method for property <tt>serviceId</tt>.
     * 
     * @param serviceId value to be assigned to property serviceId
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

}
