/**
 * com Inc
 * Copyright (c) 2014-2016 All Rights Reserved.
 */
package com.zhaoyun.docmanager.model.param;

/**
 * 
 * @author user
 * @version $Id: ServiceQueryPram.java, v 0.1 2016年8月15日 下午5:39:59 user Exp $
 */
public class ServiceQueryParam extends PagedQueryParam {

    /**  */
    private static final long serialVersionUID = 1L;

    /**  应用版本id*/
    private Integer           appVersionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_service.is_deprecated
     * 是否废弃(0：否；1：是；默认：否)
     *
     * @mbggenerated
     */
    private Integer           isDeprecated;

    /**  应用id*/
    private Integer           appId;

    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public Integer getIsDeprecated() {
        return isDeprecated;
    }

    public void setIsDeprecated(Integer isDeprecated) {
        this.isDeprecated = isDeprecated;
    }

    /**
     * Getter method for property <tt>appVersionId</tt>.
     * 
     * @return property value of appVersionId
     */
    public Integer getAppVersionId() {
        return appVersionId;
    }

    /**
     * Setter method for property <tt>appVersionId</tt>.
     * 
     * @param appVersionId value to be assigned to property appVersionId
     */
    public void setAppVersionId(Integer appVersionId) {
        this.appVersionId = appVersionId;
    }

}
