package com.zhaoyun.docmanager.dal.dao;

import com.zhaoyun.docmanager.model.dvo.DocApp;

public interface MBGDocAppDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app
     *
     * @mbggenerated
     */
    int insert(DocApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app
     *
     * @mbggenerated
     */
    int insertSelective(DocApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app
     *
     * @mbggenerated
     */
    DocApp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocApp record);
}