package com.zhaoyun.docmanager.dal.dao;

import com.zhaoyun.docmanager.model.dvo.DocAppMessage;

public interface MBGDocAppMessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_message
     *
     * @mbggenerated
     */
    int insert(DocAppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_message
     *
     * @mbggenerated
     */
    int insertSelective(DocAppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_message
     *
     * @mbggenerated
     */
    DocAppMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocAppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(DocAppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocAppMessage record);
}