package com.zhaoyun.docmanager.dal.dao;

import com.zhaoyun.docmanager.model.dvo.DocAppVersion;

public interface MBGDocAppVersionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_version
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_version
     *
     * @mbggenerated
     */
    int insert(DocAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_version
     *
     * @mbggenerated
     */
    int insertSelective(DocAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_version
     *
     * @mbggenerated
     */
    DocAppVersion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_app_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocAppVersion record);
}